[window]
padding = { x = 5, y = 5 }
position = { x = -5, y = 0 }
dimensions = { columns = 115, lines = 66 }
title = ""
dynamic_title = false
[scrolling]
history = 100000
multiplier = 5
[font]
normal = { family = "CaskaydiaCove Nerd Font", style = "SemiBold" }
bold = { family = "CaskaydiaCove Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font", style = "SemiBoldItalic" }
bold_italic = { family = "CaskaydiaCove Nerd Font", style = "BoldItalic" }
size = 10
offset = { x = 1, y = 0 }
[cursor]
style = { blinking = "Always" }
blink_interval = 450
blink_timeout = 0
[terminal]
shell = "pwsh.exe"
[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "Paste" },
  { key = "Return", mode = "Vi", action = "ToggleViMode" },
]
